# -*- coding: utf-8 -*-
"""DSA :DAY 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_823VOizTKVLcIVGK2QEG_5rrjGAi7-D
"""

#Question 1
#What is the time, space complexity of following code:
#int a = 0, b = 0;
#for (i = 0; i < N; i++) {
#a = a + 1;
#}
#for (j = 0; j < M; j++) {
#b = b + j;
#}

---> O(N + M) time complexity , O(1) space complexity.

#Question 2
#What does it mean when we say that an algorithm X is asymptotically more efficient than Y?
#a)X will be a better choice for all inputs
#b)X will be a better choice for all inputs except possibly small inputs
#c)X will be a better choice for all inputs except possibly large inputs
#d)Y will be a better choice for small inputs

---> X will be a better choice for all inputs